# Generated by Django 4.2.7 on 2023-11-26 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arrows',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrowLength', models.IntegerField(default=0)),
                ('spinage', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Bow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bowtype', models.CharField(choices=[('LongBow', 'LongBow'), ('CompoundBow', 'CompoundBow'), ('RecurveBow', 'RecurveBow')], max_length=100)),
                ('drawLength', models.IntegerField(default=0)),
                ('drawStrength', models.IntegerField(default=0)),
            ],
        ),
    ]
