# Generated by Django 4.2.7 on 2023-12-02 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TheArcheryMerchant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='arrows',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bow',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
