# Generated by Django 4.2.7 on 2023-12-04 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TheArcheryMerchant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arrows',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='bow',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
